site_name: Core API - Python Client

pages:
- Home: index.md
- API Guide:
    - Clients: api-guide/client.md
    - Documents: api-guide/document.md
    - Authentication: api-guide/auth.md
    - Codecs: api-guide/codecs.md
    - Transports: api-guide/transports.md
    - Exceptions: api-guide/exceptions.md
    - Utilities: api-guide/utils.md
- Topics:
    - Release Notes: topics/release-notes.md

repo_url: https://github.com/core-api/python-client/
copyright: Copyright &copy; 2015, <a href="https://twitter.com/_tomchristie">Tom Christie</a>.
